### ISSUE TITLE
The script that generates preprocessed cc2vec data is missing

### ISSUE THREAD

**Issue by Ringbo** [SerVal-DTF/DL4PatchCorrectness#2]
Dear authors.

Thanks for your work about patch correctness. Recently, I am performing a study about patch correctness. I encounter some problems when try to recreate your work on my dataset. Specifically, the script that generates preprocessed cc2vec vectors is missing. I can't find relative script that transforms data (generated in [here](https://github.com/SerVal-DTF/DL4PatchCorrectness/blob/master/prediction/prepare_data.py#L536)) to [pickle file](https://github.com/SerVal-DTF/DL4PatchCorrectness/blob/master/prediction/train_predict.py#L155). 
I would appreciate it if you could help me :)

Best regards.

Bo.

**Comment by Manas-Embold** [comment]
Same Problem

**Comment by HaoyeTianCoder** [comment]
> Dear authors.
> 
> Thanks for your work about patch correctness. Recently, I am performing a study about patch correctness. I encounter some problems when try to recreate your work on my dataset. Specifically, the script that generates preprocessed cc2vec vectors is missing. I can't find relative script that transforms data (generated in [here](https://github.com/SerVal-DTF/DL4PatchCorrectness/blob/master/prediction/prepare_data.py#L536)) to [pickle file](https://github.com/SerVal-DTF/DL4PatchCorrectness/blob/master/prediction/train_predict.py#L155).
> I would appreciate it if you could help me :)
> 
> Best regards.
> 
> Bo.

Hi Ringbo,

Thank you for your question. I am sorry to reply so late. I am busy with other projects. Fort the CC2V pickle, I processed it in my other repository forked from CC2Vec GitHub that I have changed a lot. [here](https://github.com/SerVal-DTF/DL4PatchCorrectness/blob/master/prediction/prepare_data.py#L536) you mentioned is the script I generated suitable input for the CC2Vec model. 

The vector process for CC2Vec is similar to Bert and Doc2vec(feed code to the pre-trained CC2Vec model, then you get the predicted vector). The only difference you need to concern about is the input of CC2Vec.

Here is the latest [CC2Vec](https://github.com/CC2Vec/CC2Vec) Github, I hope it could help you. Thank you.

Best regards,
Haoye.

**Comment by Ringbo** [comment]
> > Dear authors.
> > Thanks for your work about patch correctness. Recently, I am performing a study about patch correctness. I encounter some problems when try to recreate your work on my dataset. Specifically, the script that generates preprocessed cc2vec vectors is missing. I can't find relative script that transforms data (generated in [here](https://github.com/SerVal-DTF/DL4PatchCorrectness/blob/master/prediction/prepare_data.py#L536)) to [pickle file](https://github.com/SerVal-DTF/DL4PatchCorrectness/blob/master/prediction/train_predict.py#L155).
> > I would appreciate it if you could help me :)
> > Best regards.
> > Bo.
> 
> Hi Ringbo,
> 
> Thank you for your question. I am sorry to reply so late. I am busy with other projects. Fort the CC2V pickle, I processed it in my other repository forked from CC2Vec GitHub that I have changed a lot. [here](https://github.com/SerVal-DTF/DL4PatchCorrectness/blob/master/prediction/prepare_data.py#L536) you mentioned is the script I generated suitable input for the CC2Vec model.
> 
> The vector process for CC2Vec is similar to Bert and Doc2vec(feed code to the pre-trained CC2Vec model, then you get the predicted vector). The only difference you need to concern about is the input of CC2Vec.
> 
> Here is the latest [CC2Vec](https://github.com/CC2Vec/CC2Vec) Github, I hope it could help you. Thank you.
> 
> Best regards,
> Haoye.

I have wrote a preproccessor to generate the compatible inputs for your  CC2Vec vector's generator and it work. 
Thanks all the same.

Best regards,
Bo.

**Comment by lemon1-ui** [comment]
@HaoyeTianCoder Hi Dr Tian, sorry to bother you. When I recreated DL4PatchCorrectness-master, I encountered some issues. Could you please tell how to run the project?  I would be very grateful if you can reply. Thanks a lot in advance!
